version: '3'
services:
  nexus:
    image: 'sonatype/nexus3'
    container_name: nexus
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '10081:8081'
    volumes:
      - '/docker/nexus/data:/nexus-data'
